backend:
  name: github
  repo: systemetric/systemetric-website
  branch: master
media_folder: "content/gallery/images"
public_folder: "/gallery/images"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Home", name: "home", widget: "hidden", default: true }
          - { label: "Draft", name: "draft", widget: "hidden", default: false }
          - { label: "Body", name: "body", widget: "markdown" }
